Docker Compose installation example
Kong/demo-scene pull request #3
Opened 2021-08-16 20:24 UTC by gAmUssA

- initial commit of docker-compose for kong
- updated ignore for jetbrains

2021-08-20 13:56 UTC, hutchic requested changes
The delta between the two docker-compose files looks to be
```
      KONG_DATABASE: 'off'
```

I'd suggest use a single docker-compose with environment variables w\ sensible defaults. Adjust the Makefile to account for the two options

docker-compose.yaml
```
      KONG_DATABASE: '"${KONG_DOCKER_DATABASE:-postgres}"'
```

Makefile
```
kong-postgres:
    docker-compose up -d

kong-dbless:
   KONG_DOCKER_DATABASE=off docker-compose up -d
```

Also we could largely capture these changes in https://github.com/Kong/docker-kong/tree/master/compose no?

2021-08-20 13:56 UTC, hutchic commented on kong-docker/dbless/startDbless.sh
> +docker-compose --file docker-compose.yaml up -d
I think we have a bias for `Makefile`

2021-08-20 13:56 UTC, hutchic commented on kong-docker/dbless/docker-compose.yaml
> +      - "8444:8444"
we try to encourage not opening the admin API port unprotected to the world at large. Doing it as follows makes it only open to localhost though this won't work if you're running the docker-compose somewhere remote obviously

```suggestion
      - "127.0.0.1:8001:8001/tcp"
      - "127.0.0.1:8444:8444/tcp"
```

2021-08-31 23:15 UTC, gAmUssA commented on kong-docker/dbless/startDbless.sh
> +docker-compose --file docker-compose.yaml up -d
noted. added makefile

2021-09-09 13:37 UTC, gAmUssA commented
We will keep this one for demo purposes, and point users to production-ready in Kong-docker repo @hutchic

2021-09-09 13:38 UTC, merged